version: '3.4'

services:
  httpd:
    build:
      context: ./app/public
      dockerfile: ../../docker/httpd/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./app/public:/var/www/html/public
      - ./docker/httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/httpd/conf/vhost.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    working_dir: /var/www/html

  phpfpm:
    build:
      context: ./app
      dockerfile: ../docker/phpfpm/Dockerfile
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html/
      - ./docker/phpfpm/conf/php.ini:/usr/local/etc/php/conf.d/99-php.ini
      - ./docker/phpfpm/conf/dev.ini:/usr/local/etc/php/conf.d/99-dev.ini
      - ./docker/phpfpm/conf/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    environment:
      - APP_ENV=dev

  db:
    image: mysql:8.0
    ports:
      - '33061:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'paris2024'
      MYSQL_PASSWORD: 'paris2024'
      MYSQL_DATABASE: 'paris2024'

  webpack:
    build:
      context: ./app
      dockerfile: ../docker/webpack/Dockerfile
    volumes:
      - ./app:/usr/app/
    working_dir: /usr/app

  mail:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

volumes:
  db_data:
